export declare const CONTENT_BACKGROUND_CONNECT = "content-background-connect";
export declare const CONTENT_MESSAGE = "content-message";
export declare const EXTENSION_KEY = "__RXJS_DEVTOOLS__";
export declare const PANEL_BACKGROUND_CONNECT = "panel-background-connect";
export declare const PANEL_BACKGROUND_INIT = "panel-background-init";
export declare const PANEL_MESSAGE = "panel-message";
export declare const MESSAGE_BATCH = "batch";
export declare const MESSAGE_BROADCAST = "broadcast";
export declare const MESSAGE_CONNECT = "connect";
export declare const MESSAGE_DISCONNECT = "disconnect";
export declare const MESSAGE_REQUEST = "request";
export declare const MESSAGE_RESPONSE = "response";
//# sourceMappingURL=consts.d.ts.map