export var CONTENT_BACKGROUND_CONNECT = 'content-background-connect';
export var CONTENT_MESSAGE = 'content-message';
export var EXTENSION_KEY = '__RXJS_DEVTOOLS__';
export var PANEL_BACKGROUND_CONNECT = 'panel-background-connect';
export var PANEL_BACKGROUND_INIT = 'panel-background-init';
export var PANEL_MESSAGE = 'panel-message';
export var MESSAGE_BATCH = 'batch';
export var MESSAGE_BROADCAST = 'broadcast';
export var MESSAGE_CONNECT = 'connect';
export var MESSAGE_DISCONNECT = 'disconnect';
export var MESSAGE_REQUEST = 'request';
export var MESSAGE_RESPONSE = 'response';
//# sourceMappingURL=consts.js.map